# encoding: utf-8 
class PopulateCurrencies < ActiveRecord::Migration
  def up
    [
      { :code => "AED",  :iso_number => "784", :decimal_places => "2", :name => "United Arab Emirates dirham"},
      { :code => "AFN",  :iso_number => "971", :decimal_places => "2", :name => "Afghan afghani"},
      { :code => "ALL",  :iso_number => "008", :decimal_places => "2", :name => "Albanian lek"},
      { :code => "AMD",  :iso_number => "051", :decimal_places => "2", :name => "Armenian dram"},
      { :code => "ANG",  :iso_number => "532", :decimal_places => "2", :name => "Netherlands Antillean guilder"},
      { :code => "AOA",  :iso_number => "973", :decimal_places => "2", :name => "Angolan kwanza"},
      { :code => "ARS",  :iso_number => "032", :decimal_places => "2", :name => "Argentine peso"},
      { :code => "AUD",  :iso_number => "036", :decimal_places => "2", :name => "Australian dollar"},
      { :code => "AWG",  :iso_number => "533", :decimal_places => "2", :name => "Aruban florin"},
      { :code => "AZN",  :iso_number => "944", :decimal_places => "2", :name => "Azerbaijani manat"},
      { :code => "BAM",  :iso_number => "977", :decimal_places => "2", :name => "Bosnia and Herzegovina convertible mark"},
      { :code => "BBD",  :iso_number => "052", :decimal_places => "2", :name => "Barbados dollar"},
      { :code => "BDT",  :iso_number => "050", :decimal_places => "2", :name => "Bangladeshi taka"},
      { :code => "BGN",  :iso_number => "975", :decimal_places => "2", :name => "Bulgarian lev"},
      { :code => "BHD",  :iso_number => "048", :decimal_places => "3", :name => "Bahraini dinar"},
      { :code => "BIF",  :iso_number => "108", :decimal_places => "0", :name => "Burundian franc"},
      { :code => "BMD",  :iso_number => "060", :decimal_places => "2", :name => "Bermudian dollar (customarily known as Bermuda dollar)"},
      { :code => "BND",  :iso_number => "096", :decimal_places => "2", :name => "Brunei dollar"},
      { :code => "BOB",  :iso_number => "068", :decimal_places => "2", :name => "Boliviano"},
      { :code => "BOV",  :iso_number => "984", :decimal_places => "2", :name => "Bolivian Mvdol (funds code)"},
      { :code => "BRL",  :iso_number => "986", :decimal_places => "2", :name => "Brazilian real"},
      { :code => "BSD",  :iso_number => "044", :decimal_places => "2", :name => "Bahamian dollar"},
      { :code => "BTN",  :iso_number => "064", :decimal_places => "2", :name => "Bhutanese ngultrum"},
      { :code => "BWP",  :iso_number => "072", :decimal_places => "2", :name => "Botswana pula"},
      { :code => "BYR",  :iso_number => "974", :decimal_places => "0", :name => "Belarusian ruble"},
      { :code => "BZD",  :iso_number => "084", :decimal_places => "2", :name => "Belize dollar"},
      { :code => "CAD",  :iso_number => "124", :decimal_places => "2", :name => "Canadian dollar"},
      { :code => "CDF",  :iso_number => "976", :decimal_places => "2", :name => "Congolese franc"},
      { :code => "CHE",  :iso_number => "947", :decimal_places => "2", :name => "WIR Euro (complementary currency)"},
      { :code => "CHF",  :iso_number => "756", :decimal_places => "2", :name => "Swiss franc"},
      { :code => "CHW",  :iso_number => "948", :decimal_places => "2", :name => "WIR Franc (complementary currency)"},
      { :code => "CLF",  :iso_number => "990", :decimal_places => "0", :name => "Unidad de Fomento (funds code)"},
      { :code => "CLP",  :iso_number => "152", :decimal_places => "0", :name => "Chilean peso"},
      { :code => "CNY",  :iso_number => "156", :decimal_places => "2", :name => "Chinese yuan"},
      { :code => "COP",  :iso_number => "170", :decimal_places => "2", :name => "Colombian peso"},
      { :code => "COU",  :iso_number => "970", :decimal_places => "2", :name => "Unidad de Valor Real"},
      { :code => "CRC",  :iso_number => "188", :decimal_places => "2", :name => "Costa Rican colon"},
      { :code => "CUC",  :iso_number => "931", :decimal_places => "2", :name => "Cuban convertible peso"},
      { :code => "CUP",  :iso_number => "192", :decimal_places => "2", :name => "Cuban peso"},
      { :code => "CVE",  :iso_number => "132", :decimal_places => "0", :name => "Cape Verde escudo"},
      { :code => "CZK",  :iso_number => "203", :decimal_places => "2", :name => "Czech koruna"},
      { :code => "DJF",  :iso_number => "262", :decimal_places => "0", :name => "Djiboutian franc"},
      { :code => "DKK",  :iso_number => "208", :decimal_places => "2", :name => "Danish krone"},
      { :code => "DOP",  :iso_number => "214", :decimal_places => "2", :name => "Dominican peso"},
      { :code => "DZD",  :iso_number => "012", :decimal_places => "2", :name => "Algerian dinar"},
      { :code => "EGP",  :iso_number => "818", :decimal_places => "2", :name => "Egyptian pound"},
      { :code => "ERN",  :iso_number => "232", :decimal_places => "2", :name => "Eritrean nakfa"},
      { :code => "ETB",  :iso_number => "230", :decimal_places => "2", :name => "Ethiopian birr"},
      { :code => "EUR",  :iso_number => "978", :decimal_places => "2", :name => "Euro"},
      { :code => "FJD",  :iso_number => "242", :decimal_places => "2", :name => "Fiji dollar"},
      { :code => "FKP",  :iso_number => "238", :decimal_places => "2", :name => "Falkland Islands pound"},
      { :code => "GBP",  :iso_number => "826", :decimal_places => "2", :name => "Pound sterling"},
      { :code => "GEL",  :iso_number => "981", :decimal_places => "2", :name => "Georgian lari"},
      { :code => "GHS",  :iso_number => "936", :decimal_places => "2", :name => "Ghanaian cedi"},
      { :code => "GIP",  :iso_number => "292", :decimal_places => "2", :name => "Gibraltar pound"},
      { :code => "GMD",  :iso_number => "270", :decimal_places => "2", :name => "Gambian dalasi"},
      { :code => "GNF",  :iso_number => "324", :decimal_places => "0", :name => "Guinean franc"},
      { :code => "GTQ",  :iso_number => "320", :decimal_places => "2", :name => "Guatemalan quetzal"},
      { :code => "GYD",  :iso_number => "328", :decimal_places => "2", :name => "Guyanese dollar"},
      { :code => "HKD",  :iso_number => "344", :decimal_places => "2", :name => "Hong Kong dollar"},
      { :code => "HNL",  :iso_number => "340", :decimal_places => "2", :name => "Honduran lempira"},
      { :code => "HRK",  :iso_number => "191", :decimal_places => "2", :name => "Croatian kuna"},
      { :code => "HTG",  :iso_number => "332", :decimal_places => "2", :name => "Haitian gourde"},
      { :code => "HUF",  :iso_number => "348", :decimal_places => "2", :name => "Hungarian forint"},
      { :code => "IDR",  :iso_number => "360", :decimal_places => "0", :name => "Indonesian rupiah"},
      { :code => "ILS",  :iso_number => "376", :decimal_places => "2", :name => "Israeli new sheqel"},
      { :code => "INR",  :iso_number => "356", :decimal_places => "2", :name => "Indian rupee"},
      { :code => "IQD",  :iso_number => "368", :decimal_places => "0", :name => "Iraqi dinar"},
      { :code => "IRR",  :iso_number => "364", :decimal_places => "0", :name => "Iranian rial"},
      { :code => "ISK",  :iso_number => "352", :decimal_places => "0", :name => "Icelandic króna"},
      { :code => "JMD",  :iso_number => "388", :decimal_places => "2", :name => "Jamaican dollar"},
      { :code => "JOD",  :iso_number => "400", :decimal_places => "3", :name => "Jordanian dinar"},
      { :code => "JPY",  :iso_number => "392", :decimal_places => "0", :name => "Japanese yen"},
      { :code => "KES",  :iso_number => "404", :decimal_places => "2", :name => "Kenyan shilling"},
      { :code => "KGS",  :iso_number => "417", :decimal_places => "2", :name => "Kyrgyzstani som"},
      { :code => "KHR",  :iso_number => "116", :decimal_places => "2", :name => "Cambodian riel"},
      { :code => "KMF",  :iso_number => "174", :decimal_places => "0", :name => "Comoro franc"},
      { :code => "KPW",  :iso_number => "408", :decimal_places => "0", :name => "North Korean won"},
      { :code => "KRW",  :iso_number => "410", :decimal_places => "0", :name => "South Korean won"},
      { :code => "KWD",  :iso_number => "414", :decimal_places => "3", :name => "Kuwaiti dinar"},
      { :code => "KYD",  :iso_number => "136", :decimal_places => "2", :name => "Cayman Islands dollar"},
      { :code => "KZT",  :iso_number => "398", :decimal_places => "2", :name => "Kazakhstani tenge"},
      { :code => "LAK",  :iso_number => "418", :decimal_places => "0", :name => "Lao kip"},
      { :code => "LBP",  :iso_number => "422", :decimal_places => "0", :name => "Lebanese pound"},
      { :code => "LKR",  :iso_number => "144", :decimal_places => "2", :name => "Sri Lankan rupee"},
      { :code => "LRD",  :iso_number => "430", :decimal_places => "2", :name => "Liberian dollar"},
      { :code => "LSL",  :iso_number => "426", :decimal_places => "2", :name => "Lesotho loti"},
      { :code => "LTL",  :iso_number => "440", :decimal_places => "2", :name => "Lithuanian litas"},
      { :code => "LVL",  :iso_number => "428", :decimal_places => "2", :name => "Latvian lats"},
      { :code => "LYD",  :iso_number => "434", :decimal_places => "3", :name => "Libyan dinar"},
      { :code => "MAD",  :iso_number => "504", :decimal_places => "2", :name => "Moroccan dirham"},
      { :code => "MDL",  :iso_number => "498", :decimal_places => "2", :name => "Moldovan leu"},
      { :code => "MGA",  :iso_number => "969", :decimal_places => "0.7", :name => "Malagasy ariary"},
      { :code => "MKD",  :iso_number => "807", :decimal_places => "2", :name => "Macedonian denar"},
      { :code => "MMK",  :iso_number => "104", :decimal_places => "0", :name => "Myanma kyat"},
      { :code => "MNT",  :iso_number => "496", :decimal_places => "2", :name => "Mongolian tugrik"},
      { :code => "MOP",  :iso_number => "446", :decimal_places => "2", :name => "Macanese pataca"},
      { :code => "MRO",  :iso_number => "478", :decimal_places => "0.7", :name => "Mauritanian ouguiya"},
      { :code => "MUR",  :iso_number => "480", :decimal_places => "2", :name => "Mauritian rupee"},
      { :code => "MVR",  :iso_number => "462", :decimal_places => "2", :name => "Maldivian rufiyaa"},
      { :code => "MWK",  :iso_number => "454", :decimal_places => "2", :name => "Malawian kwacha"},
      { :code => "MXN",  :iso_number => "484", :decimal_places => "2", :name => "Mexican peso"},
      { :code => "MXV",  :iso_number => "979", :decimal_places => "2", :name => "Mexican Unidad de Inversion (UDI) (funds code)"},
      { :code => "MYR",  :iso_number => "458", :decimal_places => "2", :name => "Malaysian ringgit"},
      { :code => "MZN",  :iso_number => "943", :decimal_places => "2", :name => "Mozambican metical"},
      { :code => "NAD",  :iso_number => "516", :decimal_places => "2", :name => "Namibian dollar"},
      { :code => "NGN",  :iso_number => "566", :decimal_places => "2", :name => "Nigerian naira"},
      { :code => "NIO",  :iso_number => "558", :decimal_places => "2", :name => "Nicaraguan córdoba"},
      { :code => "NOK",  :iso_number => "578", :decimal_places => "2", :name => "Norwegian krone"},
      { :code => "NPR",  :iso_number => "524", :decimal_places => "2", :name => "Nepalese rupee"},
      { :code => "NZD",  :iso_number => "554", :decimal_places => "2", :name => "New Zealand dollar"},
      { :code => "OMR",  :iso_number => "512", :decimal_places => "3", :name => "Omani rial"},
      { :code => "PAB",  :iso_number => "590", :decimal_places => "2", :name => "Panamanian balboa"},
      { :code => "PEN",  :iso_number => "604", :decimal_places => "2", :name => "Peruvian nuevo sol"},
      { :code => "PGK",  :iso_number => "598", :decimal_places => "2", :name => "Papua New Guinean kina"},
      { :code => "PHP",  :iso_number => "608", :decimal_places => "2", :name => "Philippine peso"},
      { :code => "PKR",  :iso_number => "586", :decimal_places => "2", :name => "Pakistani rupee"},
      { :code => "PLN",  :iso_number => "985", :decimal_places => "2", :name => "Polish złoty"},
      { :code => "PYG",  :iso_number => "600", :decimal_places => "0", :name => "Paraguayan guaraní"},
      { :code => "QAR",  :iso_number => "634", :decimal_places => "2", :name => "Qatari rial"},
      { :code => "RON",  :iso_number => "946", :decimal_places => "2", :name => "Romanian new leu"},
      { :code => "RSD",  :iso_number => "941", :decimal_places => "2", :name => "Serbian dinar"},
      { :code => "RUB",  :iso_number => "643", :decimal_places => "2", :name => "Russian rouble"},
      { :code => "RWF",  :iso_number => "646", :decimal_places => "0", :name => "Rwandan franc"},
      { :code => "SAR",  :iso_number => "682", :decimal_places => "2", :name => "Saudi riyal"},
      { :code => "SBD",  :iso_number => "090", :decimal_places => "2", :name => "Solomon Islands dollar"},
      { :code => "SCR",  :iso_number => "690", :decimal_places => "2", :name => "Seychelles rupee"},
      { :code => "SDG",  :iso_number => "938", :decimal_places => "2", :name => "Sudanese pound"},
      { :code => "SEK",  :iso_number => "752", :decimal_places => "2", :name => "Swedish krona/kronor"},
      { :code => "SGD",  :iso_number => "702", :decimal_places => "2", :name => "Singapore dollar"},
      { :code => "SHP",  :iso_number => "654", :decimal_places => "2", :name => "Saint Helena pound"},
      { :code => "SLL",  :iso_number => "694", :decimal_places => "0", :name => "Sierra Leonean leone"},
      { :code => "SOS",  :iso_number => "706", :decimal_places => "2", :name => "Somali shilling"},
      { :code => "SRD",  :iso_number => "968", :decimal_places => "2", :name => "Surinamese dollar"},
      { :code => "SSP",  :iso_number => "728", :decimal_places => "2", :name => "South Sudanese pound"},
      { :code => "STD",  :iso_number => "678", :decimal_places => "0", :name => "São Tomé and Príncipe dobra"},
      { :code => "SYP",  :iso_number => "760", :decimal_places => "2", :name => "Syrian pound"},
      { :code => "SZL",  :iso_number => "748", :decimal_places => "2", :name => "Swazi lilangeni"},
      { :code => "THB",  :iso_number => "764", :decimal_places => "2", :name => "Thai baht"},
      { :code => "TJS",  :iso_number => "972", :decimal_places => "2", :name => "Tajikistani somoni"},
      { :code => "TMT",  :iso_number => "934", :decimal_places => "2", :name => "Turkmenistani manat"},
      { :code => "TND",  :iso_number => "788", :decimal_places => "3", :name => "Tunisian dinar"},
      { :code => "TOP",  :iso_number => "776", :decimal_places => "2", :name => "Tongan paʻanga"},
      { :code => "TRY",  :iso_number => "949", :decimal_places => "2", :name => "Turkish lira"},
      { :code => "TTD",  :iso_number => "780", :decimal_places => "2", :name => "Trinidad and Tobago dollar"},
      { :code => "TWD",  :iso_number => "901", :decimal_places => "2", :name => "New Taiwan dollar"},
      { :code => "TZS",  :iso_number => "834", :decimal_places => "2", :name => "Tanzanian shilling"},
      { :code => "UAH",  :iso_number => "980", :decimal_places => "2", :name => "Ukrainian hryvnia"},
      { :code => "UGX",  :iso_number => "800", :decimal_places => "2", :name => "Ugandan shilling"},
      { :code => "USD",  :iso_number => "840", :decimal_places => "2", :name => "United States dollar"},
      { :code => "USN",  :iso_number => "997", :decimal_places => "2", :name => "United States dollar (next day) (funds code)"},
      { :code => "USS",  :iso_number => "998", :decimal_places => "2", :name => "United States dollar (same day) (funds code) (one source[who?] claims it is no longer used, but it is still on the ISO 4217-MA list)"},
      { :code => "UYI",  :iso_number => "940", :decimal_places => "0", :name => "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)"},
      { :code => "UYU",  :iso_number => "858", :decimal_places => "2", :name => "Uruguayan peso"},
      { :code => "UZS",  :iso_number => "860", :decimal_places => "2", :name => "Uzbekistan som"},
      { :code => "VEF",  :iso_number => "937", :decimal_places => "2", :name => "Venezuelan bolívar fuerte"},
      { :code => "VND",  :iso_number => "704", :decimal_places => "0", :name => "Vietnamese đồng"},
      { :code => "VUV",  :iso_number => "548", :decimal_places => "0", :name => "Vanuatu vatu"},
      { :code => "WST",  :iso_number => "882", :decimal_places => "2", :name => "Samoan tala"},
      { :code => "XAF",  :iso_number => "950", :decimal_places => "0", :name => "CFA franc BEAC"},
      { :code => "XAG",  :iso_number => "961", :decimal_places => "5", :name => "Silver (one troy ounce) "},
      { :code => "XAU",  :iso_number => "959", :decimal_places => "5", :name => "Gold (one troy ounce) "},
      { :code => "XBA",  :iso_number => "955", :decimal_places => "5", :name => "European Composite Unit (EURCO) (bond market unit)"},
      { :code => "XBB",  :iso_number => "956", :decimal_places => "5", :name => "European Monetary Unit (E.M.U.-6) (bond market unit)"},
      { :code => "XBC",  :iso_number => "957", :decimal_places => "5", :name => "European Unit of Account 9 (E.U.A.-9) (bond market unit)"},
      { :code => "XBD",  :iso_number => "958", :decimal_places => "5", :name => "European Unit of Account 17 (E.U.A.-17) (bond market unit)"},
      { :code => "XCD",  :iso_number => "951", :decimal_places => "2", :name => "East Caribbean dollar"},
      { :code => "XDR",  :iso_number => "960", :decimal_places => "5", :name => "Special drawing rights"},
      { :code => "XFU",  :iso_number => "Nil", :decimal_places => "5", :name => "UIC franc (special settlement currency) International Union of Railways"},
      { :code => "XOF",  :iso_number => "952", :decimal_places => "0", :name => "CFA Franc BCEAO"},
      { :code => "XPD",  :iso_number => "964", :decimal_places => "5", :name => "Palladium (one troy ounce)"},
      { :code => "XPF",  :iso_number => "953", :decimal_places => "0", :name => "CFP franc"},
      { :code => "XPT",  :iso_number => "962", :decimal_places => "5", :name => "Platinum (one troy ounce) "},
      { :code => "XTS",  :iso_number => "963", :decimal_places => "5", :name => "Code reserved for testing purposes"},
      { :code => "XXX",  :iso_number => "999", :decimal_places => "5", :name => "No currency "},
      { :code => "YER",  :iso_number => "886", :decimal_places => "2", :name => "Yemeni rial"},
      { :code => "ZAR",  :iso_number => "710", :decimal_places => "2", :name => "South African rand"},
      { :code => "ZMK",  :iso_number => "894", :decimal_places => "2", :name => "Zambian kwacha"},
      { :code => "ZWL",  :iso_number => "932", :decimal_places => "2", :name => "Zimbabwe dollar"},
    ].each { |currency| Currency.create! currency }  
  end

  def down
    Currency.delete_all
  end
end

